server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  # eureka 服务器的实例名称
  client:
    register-with-eureka: false #是否将自己注册到 Eureka-Server 中，默认的为 true
    fetch-registry: false #是否需要拉取服务信息，默认未true
      # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka



