server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  # eureka 服务器的实例名称
  client:
    register-with-eureka: false #是否将自己注册到 Eureka-Server 中，默认的为 true
    fetch-registry: false #是否需要拉取服务信息，默认未true
      # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
    service-url:
      ##集群就是指向其他eureka
#      defaultZone: http://eureka7002.com:7002/eureka
      ##单机就是指向自己
      defaultZone: http://eureka7001.com:7001/eureka
#  server:
#    enable-self-preservation: false  #关闭自我保护机制 保证不可用服务及时被踢出
#    eviction-interval-timer-in-ms: 2000



